import type { WorldEvent, AgentStats, ChatMessage } from '@lore/shared';
import type { LLMScheduler } from '../llm/scheduler.js';
import type { LoreConfig } from '../config/loader.js';
import type { Repository } from '../db/repository.js';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { createLogger } from '../logger/index.js';

const logger = createLogger('world-agent');

const WorldAgentDecisionSchema = z.object({
  shouldAct: z.boolean().default(false),
  eventType: z.enum(['disaster', 'economic', 'social', 'political', 'health', 'weather', 'none']).default('none'),
  eventCategory: z.string().default('未知事件'),
  description: z.string().max(200).default('发生了一些事'),
  severity: z.enum(['minor', 'moderate', 'major', 'catastrophic']).default('minor'),
  affectedAgentCriteria: z.object({
    occupation: z.array(z.string()).optional(),
    moodRange: z.tuple([z.number(), z.number()]).optional(),
    random: z.number().min(0).max(1).optional(),
    all: z.boolean().optional(),
  }).default({}),
  consequences: z.object({
    statChanges: z.object({
      mood: z.number().optional(),
      health: z.number().optional(),
      energy: z.number().optional(),
      money: z.number().optional(),
    }).default({}),
    relationshipModifier: z.number().optional(),
  }).default({ statChanges: {} }),
  reasoning: z.string().default(''),
  probability: z.number().min(0).max(1).default(0.5),
});

export interface WorldStateSummary {
  currentTick: number;
  currentTime: string;
  day: number;
  worldId: string;
  agentCount: number;
  avgMood: number;
  avgHealth: number;
  avgEnergy: number;
  avgMoney: number;
  moodDistribution: { happy: number; neutral: number; sad: number };
  employmentRate: number;
  recentEvents: string[];
}

export interface WorldAgentDecision {
  shouldAct: boolean;
  eventType: 'disaster' | 'economic' | 'social' | 'political' | 'health' | 'weather' | 'none';
  eventCategory: string;
  description: string;
  severity: 'minor' | 'moderate' | 'major' | 'catastrophic';
  affectedAgentCriteria: {
    occupation?: string[];
    moodRange?: [number, number];
    random?: number;
    all?: boolean;
  };
  consequences: {
    statChanges: Partial<AgentStats>;
    relationshipModifier?: number;
  };
  reasoning: string;
  probability: number;
}

export class WorldAgent {
  private llmScheduler: LLMScheduler;
  private config: LoreConfig;
  private repo: Repository;
  private lastThinkTick = 0;
  private thinkInterval = 15;
  private pendingEvents: WorldEvent[] = [];
  private worldHistory: string[] = [];

  constructor(llmScheduler: LLMScheduler, config: LoreConfig, repo: Repository) {
    this.llmScheduler = llmScheduler;
    this.config = config;
    this.repo = repo;
  }

  setRepo(repo: Repository): void {
    this.repo = repo;
  }

  async think(worldState: WorldStateSummary, agents: Array<{
    id: string;
    profile: { name: string; occupation: string };
    stats: AgentStats;
    state: { status: string };
  }>): Promise<WorldEvent[]> {
    if (worldState.currentTick - this.lastThinkTick < this.thinkInterval) {
      return this.processPendingEvents(worldState);
    }

    this.lastThinkTick = worldState.currentTick;

    const shouldThink = this.shouldTriggerWorldEvent(worldState);
    if (!shouldThink) {
      return this.generateMinorWeatherEvent(worldState);
    }

    try {
      const decision = await this.makeLLMDecision(worldState, agents);
      if (decision && decision.shouldAct && decision.eventType !== 'none') {
        const event = this.createWorldEvent(decision, worldState, agents);
        if (event) {
          this.worldHistory.push(`${worldState.day}天:${event.description}`);
          if (this.worldHistory.length > 50) {
            this.worldHistory.shift();
          }
          logger.info({
            tick: worldState.currentTick,
            type: decision.eventType,
            severity: decision.severity,
            description: event.description,
          }, 'World event generated by LLM');
          return [event];
        }
      }
    } catch (err) {
      logger.warn({ tick: worldState.currentTick, err }, 'World Agent LLM decision failed, using fallback');
      return this.generateFallbackEvent(worldState, agents);
    }

    return this.generateMinorWeatherEvent(worldState);
  }

  private shouldTriggerWorldEvent(worldState: WorldStateSummary): boolean {
    if (worldState.avgMood < 30) return true;
    if (worldState.avgHealth < 50) return true;
    if (worldState.employmentRate < 0.3) return true;
    if (worldState.day % 7 === 0 && Math.random() < 0.2) return true;
    if (worldState.currentTick % 100 === 0 && Math.random() < 0.15) return true;
    return Math.random() < 0.05;
  }

  private async makeLLMDecision(
    worldState: WorldStateSummary,
    agents: Array<{
      id: string;
      profile: { name: string; occupation: string };
      stats: AgentStats;
      state: { status: string };
    }>,
  ): Promise<WorldAgentDecision | null> {
    const prompt = this.buildWorldDecisionPrompt(worldState, agents);

    const result = await this.llmScheduler.submit({
      agentId: 'world-agent',
      callType: 'world-event',
      model: this.config.llm.defaults.standardModel,
      messages: prompt,
      maxTokens: 1024,
    });

    try {
      const parsed = JSON.parse(result.content);
      return this.validateDecision(parsed);
    } catch {
      logger.warn({ content: result.content.slice(0, 200) }, 'Failed to parse World Agent decision');
      return null;
    }
  }

  private buildWorldDecisionPrompt(
    worldState: WorldStateSummary,
    agents: Array<{
      id: string;
      profile: { name: string; occupation: string };
      stats: AgentStats;
      state: { status: string };
    }>,
  ): ChatMessage[] {
    const recentHistory = this.worldHistory.slice(-10).join('\n');
    const agentSummary = this.summarizeAgents(agents);

    return [
      {
        role: 'system' as const,
        content: `你是 World Agent，负责管理虚拟世界的宏观事件和变化。

你的职责：
1. 监控世界整体状态（经济、社会氛围、Agent 健康/心情分布）
2. 在必要时触发世界级事件
3. 确保世界有足够的变化和戏剧性，但不至于崩溃

事件类型：
- disaster: 自然灾害（地震、洪水、火灾、疫情）
- economic: 经济事件（股市崩盘、公司倒闭、经济繁荣、通货膨胀）
- social: 社会事件（流行趋势、文化事件、社会运动）
- political: 政治事件（政策变化、选举、法律）
- health: 健康 events（流感爆发、食品安全问题）
- weather: 天气事件（极端天气）

严重程度：
- minor: 小影响，少数人受影响
- moderate: 中等影响，部分群体受影响
- major: 大影响，广泛群体受影响
- catastrophic: 灾难级，几乎所有人受影响

规则：
- 世界平均心情过低时可考虑正向事件提振
- 世界过于平静时可适度制造变化
- 不要过于频繁触发重大事件
- 事件要符合世界设定和逻辑`,
      },
      {
        role: 'user' as const,
        content: `当前世界状态：

时间：第 ${worldState.day} 天，${worldState.currentTime}
Agent 数量：${worldState.agentCount}
平均心情：${worldState.avgMood.toFixed(1)}/100
平均健康：${worldState.avgHealth.toFixed(1)}/100
平均精力：${worldState.avgEnergy.toFixed(1)}/100
就业率：${(worldState.employmentRate * 100).toFixed(1)}%

心情分布：
- 开心(${worldState.moodDistribution.happy}人) / 一般(${worldState.moodDistribution.neutral}人) / 低落(${worldState.moodDistribution.sad}人)

Agent 职业分布：
${agentSummary}

近期世界历史：
${recentHistory || '（无重大事件）'}

请决定是否触发世界事件。返回 JSON：
{
  "shouldAct": true/false,
  "eventType": "事件类型",
  "eventCategory": "具体类别（如：地震、流感、股市上涨）",
  "description": "事件描述（1-2句话，生动描述）",
  "severity": "严重程度",
  "affectedAgentCriteria": {
    "occupation": ["受影响职业（可选）"],
    "moodRange": [最低心情, 最高心情]（可选）,
    "random": 随机影响比例0-1（可选）,
    "all": true/false（是否影响所有人）
  },
  "consequences": {
    "statChanges": { "mood": 数值变化, "health": 数值变化, "money": 数值变化 },
    "relationshipModifier": 关系变化系数（可选）
  },
  "reasoning": "为什么触发这个事件",
  "probability": 触发概率0-1
}`,
      },
    ];
  }

  private summarizeAgents(agents: Array<{
    id: string;
    profile: { name: string; occupation: string };
    stats: AgentStats;
    state: { status: string };
  }>): string {
    const occupationCounts: Record<string, number> = {};
    for (const a of agents) {
      const occ = a.profile.occupation || '无业';
      occupationCounts[occ] = (occupationCounts[occ] || 0) + 1;
    }
    return Object.entries(occupationCounts)
      .map(([occ, count]) => `- ${occ}: ${count}人`)
      .join('\n');
  }

  private validateDecision(parsed: unknown): WorldAgentDecision | null {
    if (!parsed || typeof parsed !== 'object') return null;

    const result = WorldAgentDecisionSchema.safeParse(parsed);
    if (!result.success) {
      logger.warn({ 
        errors: result.error.errors, 
        parsed: JSON.stringify(parsed).slice(0, 200) 
      }, 'World Agent decision validation failed');
      return null;
    }

    const d = result.data;

    return {
      shouldAct: d.shouldAct,
      eventType: d.eventType,
      eventCategory: d.eventCategory,
      description: d.description,
      severity: d.severity,
      affectedAgentCriteria: {
        occupation: d.affectedAgentCriteria.occupation,
        moodRange: d.affectedAgentCriteria.moodRange,
        random: d.affectedAgentCriteria.random,
        all: d.affectedAgentCriteria.all,
      },
      consequences: {
        statChanges: d.consequences.statChanges,
        relationshipModifier: d.consequences.relationshipModifier,
      },
      reasoning: d.reasoning,
      probability: d.probability,
    };
  }

  private createWorldEvent(
    decision: WorldAgentDecision,
    worldState: WorldStateSummary,
    agents: Array<{
      id: string;
      profile: { name: string; occupation: string };
      stats: AgentStats;
      state: { status: string };
    }>,
  ): WorldEvent | null {
    if (Math.random() > decision.probability) {
      logger.debug({ decision: decision.eventCategory }, 'World event skipped by probability');
      return null;
    }

    const affectedIds = this.selectAffectedAgents(decision, agents);

    const severityMultiplier = {
      minor: 1,
      moderate: 2,
      major: 3,
      catastrophic: 5,
    };

    const mult = severityMultiplier[decision.severity] || 1;
    const consequences = affectedIds.map((id) => ({
      agentId: id,
      statChanges: {
        mood: Math.round((decision.consequences.statChanges.mood || 0) * mult),
        health: Math.round((decision.consequences.statChanges.health || 0) * mult),
        energy: Math.round((decision.consequences.statChanges.energy || 0) * mult),
        money: Math.round((decision.consequences.statChanges.money || 0) * mult),
      },
    }));

    return {
      id: nanoid(),
      worldId: worldState.worldId,
      type: 'world',
      category: decision.eventCategory,
      description: decision.description,
      involvedAgents: affectedIds,
      consequences,
      timestamp: new Date(),
      processed: false,
      priority: this.calculatePriority(decision.severity),
      userChoices: this.generateUserChoices(decision),
    };
  }

  private selectAffectedAgents(
    decision: WorldAgentDecision,
    agents: Array<{
      id: string;
      profile: { name: string; occupation: string };
      stats: AgentStats;
      state: { status: string };
    }>,
  ): string[] {
    const criteria = decision.affectedAgentCriteria;

    if (criteria.all) {
      return agents.filter((a) => a.state.status !== 'dead').map((a) => a.id);
    }

    let candidates = agents.filter((a) => a.state.status !== 'dead');

    if (criteria.occupation && criteria.occupation.length > 0) {
      candidates = candidates.filter((a) =>
        criteria.occupation!.some((occ) =>
          a.profile.occupation.toLowerCase().includes(occ.toLowerCase()),
        ),
      );
    }

    if (criteria.moodRange) {
      const [min, max] = criteria.moodRange;
      candidates = candidates.filter((a) => a.stats.mood >= min && a.stats.mood <= max);
    }

    if (criteria.random) {
      const count = Math.ceil(candidates.length * criteria.random);
      candidates = candidates.sort(() => Math.random() - 0.5).slice(0, Math.max(1, count));
    }

    return candidates.map((a) => a.id);
  }

  private calculatePriority(severity: WorldAgentDecision['severity']): number {
    const priorityMap = {
      minor: 30,
      moderate: 50,
      major: 70,
      catastrophic: 90,
    };
    return priorityMap[severity] || 30;
  }

  private generateUserChoices(decision: WorldAgentDecision): string[] | undefined {
    if (decision.severity === 'catastrophic') {
      return ['尽力帮助他人', '保护好自己', '观察事态发展'];
    }
    if (decision.severity === 'major') {
      return ['主动应对', '静观其变'];
    }
    return undefined;
  }

  private generateFallbackEvent(
    worldState: WorldStateSummary,
    agents: Array<{
      id: string;
      profile: { name: string; occupation: string };
      stats: AgentStats;
      state: { status: string };
    }>,
  ): WorldEvent[] {
    const fallbacks = [
      {
        eventCategory: '天气变化',
        description: '今天天气突然变化，影响了大家的出行计划',
        severity: 'minor' as const,
        statChanges: { mood: -5 },
        probability: 0.3,
      },
      {
        eventCategory: '小规模流感',
        description: '最近有小规模流感传播，部分人身体不适',
        severity: 'minor' as const,
        statChanges: { health: -10, energy: -5 },
        affectedCriteria: { random: 0.2 },
        probability: 0.2,
      },
      {
        eventCategory: '好消息传播',
        description: '城市里传来了一些好消息，大家心情好转',
        severity: 'minor' as const,
        statChanges: { mood: 10 },
        probability: 0.15,
      },
    ];

    const selected = fallbacks[Math.floor(Math.random() * fallbacks.length)];
    if (!selected || Math.random() > selected.probability) {
      return this.generateMinorWeatherEvent(worldState);
    }

    const affectedIds = selected.affectedCriteria
      ? agents
          .filter((a) => a.state.status !== 'dead')
          .sort(() => Math.random() - 0.5)
          .slice(0, Math.ceil(agents.length * (selected.affectedCriteria.random || 0.2)))
          .map((a) => a.id)
      : agents.filter((a) => a.state.status !== 'dead').map((a) => a.id);

    return [
      {
        id: nanoid(),
        worldId: worldState.worldId,
        type: 'world',
        category: selected.eventCategory,
        description: selected.description,
        involvedAgents: affectedIds,
        consequences: affectedIds.map((id) => ({
          agentId: id,
          statChanges: selected.statChanges,
        })),
        timestamp: new Date(),
        processed: false,
        priority: 30,
      },
    ];
  }

  private generateMinorWeatherEvent(worldState: WorldStateSummary): WorldEvent[] {
    if (Math.random() > 0.3) return [];

    const weathers = [
      { desc: '今天阳光明媚', moodChange: 3 },
      { desc: '天空飘着小雨', moodChange: -2 },
      { desc: '微风吹过，天气舒适', moodChange: 1 },
      { desc: '天气闷热，让人有点烦躁', moodChange: -3 },
      { desc: '清晨有薄雾，空气清新', moodChange: 2 },
    ];

    const weather = weathers[Math.floor(Math.random() * weathers.length)]!;
    if (!weather) return [];

    return [
      {
        id: nanoid(),
        worldId: worldState.worldId,
        type: 'world',
        category: 'weather',
        description: weather.desc,
        involvedAgents: [],
        consequences: [],
        timestamp: new Date(),
        processed: false,
        priority: 20,
      },
    ];
  }

  private processPendingEvents(worldState: WorldStateSummary): WorldEvent[] {
    const events: WorldEvent[] = [];
    for (const event of this.pendingEvents) {
      if (event.timestamp <= new Date()) {
        events.push(event);
      }
    }
    this.pendingEvents = this.pendingEvents.filter((e) => !events.includes(e));
    return events;
  }

  scheduleEvent(event: WorldEvent, delayMs: number): void {
    const scheduledEvent = {
      ...event,
      timestamp: new Date(Date.now() + delayMs),
    };
    this.pendingEvents.push(scheduledEvent);
    logger.debug({ eventId: event.id, delayMs }, 'Event scheduled');
  }

  getWorldHistory(): string[] {
    return this.worldHistory;
  }
}